allowBuilds:
  '@parcel/watcher': true
  esbuild: false
  sharp: false
  workerd: false
minimumReleaseAgeExclude:
  - astro-tailwind-autoref@1.0.0
  - astro-tailwind-autoref@1.0.2
  - astro-tailwind-autoref@1.0.5
packages:
  - "*"
